server:
  port: 8083

spring:
  application:
    name: FoodDelivery

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_GOOGLE_CLIENT_ID
            client-secret: YOUR_GOOGLE_CLIENT_SECRET
            scope: openid, profile, email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    # For a file-based database
    url: jdbc:h2:file:/data/devDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: chhavi
    password: cutie

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  jackson:
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - beans
          - mappings
